# Generated by scripts/homebrew-release.py from a published CLI archive.
class Greenbubbles < Formula
  desc "Read your own WeChat history locally and provide bounded context to agents"
  homepage "https://github.com/bojieli/greenbubbles"
  url "https://github.com/bojieli/greenbubbles/releases/download/v0.3.0/greenbubbles-0.3.0-macos-arm64.zip"
  sha256 "017767b9d2c1f32039eba06f531e335b74fe8a1dfd19100c1cb7b89d49bba22a"
  license "MIT"

  depends_on arch: :arm64
  depends_on macos: :sonoma

  # Preserve upstream Developer ID signatures on the notarized executables.
  skip_clean "libexec"

  def install
    libexec.install Dir["*"]
    bin.install_symlink (libexec/"bin").children
  end

  def caveats
    <<~EOS
      This installs the signed Apple-silicon CLI/tool set, not the native app.
      Documentation and skills shipped in this release are under:
        #{opt_libexec}
      Point your coding agent at a SKILL.md there; skill installation is optional.
      Source/profile setup and owner-operated key capture are separate steps.
    EOS
  end

  test do
    assert_match "Usage", shell_output("#{bin}/greenbubbles --help")
    assert_match "memory", shell_output("#{bin}/greenbubbles memory --help")
  end
end
