# Generated by scripts/homebrew-release.py from a published CLI archive.
class Greenbubbles < Formula
  desc "Read your own WeChat history locally and provide bounded context to agents"
  homepage "https://github.com/bojieli/greenbubbles"
  url "https://github.com/bojieli/greenbubbles/releases/download/v0.9.4/greenbubbles-0.9.4-macos-arm64.zip"
  sha256 "068c4c3e7c64fc981adf88c7ccd72f0cd3f9da1899f8b697ff4fa43a898871a3"
  license "MIT"
  revision 1

  depends_on arch: :arm64
  depends_on macos: :sonoma

  # Preserve upstream Developer ID signatures on the notarized executables.
  skip_clean "libexec"

  def install
    libexec.install Dir["*"]
    bin.install_symlink (libexec/"bin").children
  end

  post_install_steps do
    # Homebrew moves top-level documentation out of libexec during installation.
    # Keep the portable bundle's license lookup valid after that relocation.
    symlink "LICENSE", "libexec/LICENSE", overwrite: true
  end

  def caveats
    <<~EOS
      This installs the signed Apple-silicon CLI/tool set, not the native app.
      Documentation and skills shipped in this release are under:
        #{opt_libexec}
      Point your coding agent at a SKILL.md there; skill installation is optional.
      Source/profile setup and owner-operated key capture are separate steps.
    EOS
  end

  test do
    assert_match "Usage", shell_output("#{bin}/greenbubbles --help 2>&1")
    assert_match "memory", shell_output("#{bin}/greenbubbles memory --help 2>&1")
  end
end
